import fs from 'fs';
import zlib from 'zlib';
import type { LayoutOptions, NodeStyleOverrides, EdgeStyleOverrides, GroupStyleOverrides } from '../layout/elkLayout.js';
import { htmlDecode } from '../utils/xmlEncoding.js';
import { extractAttr, extractGeometry, computeAbsCoords } from '../utils/mxCellUtils.js';
import { parseStyleMap } from '../utils/styleMerging.js';

export interface ParsedNode {
  id: string;
  label: string;
  icon_data_uri?: string;
  highlight?: string;
  /** Absolute X coordinate extracted from mxGeometry (for INTERACTIVE ELK layout hint) */
  x_hint?: number;
  /** Absolute Y coordinate extracted from mxGeometry (for INTERACTIVE ELK layout hint) */
  y_hint?: number;
  /** Raw mxGeometry x — top-level=absolute, inside group=group-relative (for preserve mode) */
  x_geom: number;
  /** Raw mxGeometry y (for preserve mode) */
  y_geom: number;
  /** mxGeometry width (for preserve mode) */
  width: number;
  /** mxGeometry height (for preserve mode) */
  height: number;
  /** Extracted visual style overrides (non-default properties only) */
  style_overrides?: NodeStyleOverrides;
}

export interface ParsedEdge {
  source: string;
  target: string;
  label?: string;
  style?: 'solid' | 'dashed';
  connector?: 'straight' | 'orthogonal' | 'elbow-h' | 'elbow-v';
  arrow?: 'default' | 'none' | 'both';
  exitX?: number;
  exitY?: number;
  entryX?: number;
  entryY?: number;
  /** Extracted visual style overrides (non-default properties only) */
  style_overrides?: EdgeStyleOverrides;
}

export interface ParsedGroup {
  id: string;
  label: string;
  children: string[];
  style?: string;
  /** mxGeometry x — top-level=absolute, nested=parent-relative (for preserve mode) */
  x: number;
  y: number;
  width: number;
  height: number;
  /** Extracted visual style overrides (non-default properties only) */
  style_overrides?: GroupStyleOverrides;
}

export interface DiagramSpec {
  nodes: ParsedNode[];
  edges: ParsedEdge[];
  groups: ParsedGroup[];
  layout?: LayoutOptions;
  output_path: string;
}

// ─── Raw cell from XML parse ─────────────────────────────────────────────────

interface RawCell {
  numericId: string;
  value: string;
  style: string;
  isVertex: boolean;
  isEdge: boolean;
  parent: string;
  source: string;
  target: string;
  x: number;
  y: number;
  width: number;
  height: number;
}

// ─── Format detection ─────────────────────────────────────────────────────────

/**
 * Detect whether a .drawio.svg file was generated by this MCP tool (Format A)
 * or created/saved by the draw.io desktop app (Format B).
 *
 * Format A: content attribute contains `<mxGraphModel>` directly (uncompressed).
 * Format B: content attribute contains `<mxfile><diagram>BASE64_COMPRESSED</diagram></mxfile>`.
 */
export function detectDrawioFormat(svgContent: string): 'A' | 'B' | 'unknown' {
  const match = svgContent.match(/\bcontent="([\s\S]*?)(?="(?:\s|\/?>|\s+data-))/);
  if (!match) return 'unknown';
  const decoded = htmlDecode(match[1]);
  if (decoded.startsWith('<mxGraphModel')) return 'A';
  if (decoded.startsWith('<mxfile')) return 'B';
  return 'unknown';
}

// ─── Public entry point ───────────────────────────────────────────────────────

export function parseDrawioSvgFile(filePath: string): DiagramSpec {
  const content = fs.readFileSync(filePath, 'utf-8');
  return parseDrawioSvgContent(content, filePath);
}

export function parseDrawioSvgContent(svgContent: string, filePath: string): DiagramSpec {
  const mxXml = extractMxGraphModelXml(svgContent);
  const layoutOptions = extractLayoutOptions(svgContent);
  const cells = parseMxCells(mxXml);
  return buildDiagramSpec(cells, layoutOptions, filePath);
}

// ─── Extract mxGraphModel XML from SVG content attribute ─────────────────────

function extractMxGraphModelXml(svgContent: string): string {
  // The content attribute may be very long; match across lines
  // It is HTML-entity encoded: &lt; &gt; &quot; &amp;
  const match = svgContent.match(/\bcontent="([\s\S]*?)(?="(?:\s|\/?>|\s+data-))/);
  if (!match) {
    throw new Error('No content attribute found in SVG file. Is this a valid .drawio.svg file?');
  }
  const decoded = htmlDecode(match[1]);

  // Format A (MCP-generated): content is directly the mxGraphModel XML
  if (decoded.startsWith('<mxGraphModel')) {
    return decoded;
  }

  // Format B (draw.io app): content is <mxfile><diagram>BASE64_COMPRESSED_XML</diagram></mxfile>
  // The diagram content is: URL-encoded XML → deflate-raw compress → base64 encode
  if (decoded.startsWith('<mxfile')) {
    const diagramMatch = decoded.match(/<diagram[^>]*>([\s\S]*?)<\/diagram>/);
    if (!diagramMatch) {
      throw new Error('Could not find <diagram> element in mxfile content.');
    }
    const base64Data = diagramMatch[1].trim();
    if (!base64Data) {
      throw new Error('Empty <diagram> content in mxfile.');
    }
    // Some draw.io versions embed the XML directly (uncompressed) inside <diagram>
    if (base64Data.startsWith('<mxGraphModel')) {
      return base64Data;
    }
    const compressed = Buffer.from(base64Data, 'base64');
    const decompressed = zlib.inflateRawSync(compressed).toString('utf-8');
    return decodeURIComponent(decompressed);
  }

  throw new Error('Unrecognized drawio content format (expected <mxGraphModel> or <mxfile>).');
}

// ─── Extract data-layout attribute ───────────────────────────────────────────

function extractLayoutOptions(svgContent: string): LayoutOptions | undefined {
  const match = svgContent.match(/\bdata-layout='([^']+)'/);
  if (!match) return undefined;
  try {
    return JSON.parse(match[1]) as LayoutOptions;
  } catch {
    return undefined;
  }
}

// ─── Parse mxCell elements ────────────────────────────────────────────────────

function parseMxCells(xml: string): RawCell[] {
  const cells: RawCell[] = [];
  // Match each mxCell tag (self-closing or with children)
  const cellRegex = /<mxCell\s([\s\S]*?)(?:>[\s\S]*?<\/mxCell>|\/>)/g;
  let m: RegExpExecArray | null;

  while ((m = cellRegex.exec(xml)) !== null) {
    const attrs = m[1];
    const numericId = extractAttr(attrs, 'id') ?? '';
    // Skip structural cells
    if (numericId === '0' || numericId === '1') continue;

    const value = htmlDecode(extractAttr(attrs, 'value') ?? '');
    const style = extractAttr(attrs, 'style') ?? '';
    const isVertex = /\bvertex="1"/.test(attrs);
    const isEdge = /\bedge="1"/.test(attrs);
    const parent = extractAttr(attrs, 'parent') ?? '1';
    const source = extractAttr(attrs, 'source') ?? '';
    const target = extractAttr(attrs, 'target') ?? '';

    // Extract mxGeometry from the full match
    const geom = extractGeometry(m[0]);

    cells.push({
      numericId,
      value,
      style,
      isVertex,
      isEdge,
      parent,
      source,
      target,
      x: geom.x,
      y: geom.y,
      width: geom.width,
      height: geom.height,
    });
  }

  return cells;
}


// ─── Build DiagramSpec from raw cells ────────────────────────────────────────

function buildDiagramSpec(
  cells: RawCell[],
  layoutOptions: LayoutOptions | undefined,
  filePath: string,
): DiagramSpec {
  // Determine which numeric IDs are group containers (have at least one child with vertex=1)
  const groupIds = new Set<string>();
  for (const c of cells) {
    if (c.isVertex && c.parent !== '1' && c.parent !== '0') {
      groupIds.add(c.parent);
    }
  }
  // Also mark groups that are children of other groups
  for (const c of cells) {
    if (c.isVertex && groupIds.has(c.numericId)) {
      if (c.parent !== '1' && c.parent !== '0') {
        groupIds.add(c.parent);
      }
    }
  }

  // Compute absolute coordinates for each vertex cell
  const absCoords = computeAbsCoords(cells, groupIds);

  // Build a set of known vertex numeric IDs for edge validation
  const vertexIds = new Set(cells.filter((c) => c.isVertex).map((c) => c.numericId));

  // Classify cells — use draw.io's native numeric IDs directly
  const nodes: ParsedNode[] = [];
  const groups: ParsedGroup[] = [];
  const edges: ParsedEdge[] = [];

  for (const c of cells) {
    if (c.isEdge) {
      if (!vertexIds.has(c.source) || !vertexIds.has(c.target)) continue; // skip dangling edges
      const arrow = classifyArrow(c.style);
      const edgeSo = extractEdgeStyleOverrides(c.style);
      edges.push({
        source: c.source,
        target: c.target,
        label: c.value || undefined,
        style: c.style.includes('dashed=1') ? 'dashed' : 'solid',
        connector: classifyConnector(c.style),
        ...(arrow !== 'default' ? { arrow } : {}),
        ...extractConnectionPoints(c.style),
        ...(edgeSo ? { style_overrides: edgeSo } : {}),
      });
    } else if (c.isVertex) {
      if (groupIds.has(c.numericId)) {
        // Group cell
        const children = cells
          .filter((child) => child.isVertex && child.parent === c.numericId)
          .map((child) => child.numericId);
        const groupSo = extractGroupStyleOverrides(c.style);
        groups.push({
          id: c.numericId,
          label: c.value,
          children,
          style: classifyGroupStyle(c.style),
          x: c.x,
          y: c.y,
          width: c.width,
          height: c.height,
          ...(groupSo ? { style_overrides: groupSo } : {}),
        });
      } else {
        // Node cell
        const abs = absCoords.get(c.numericId) ?? { x: c.x, y: c.y };
        const isIcon = c.style.includes('shape=image');
        const node: ParsedNode = {
          id: c.numericId,
          label: c.value,
          x_hint: abs.x,
          y_hint: abs.y,
          x_geom: c.x,
          y_geom: c.y,
          width: c.width,
          height: c.height,
        };
        const iconDataUri = extractIconDataUri(c.style);
        if (iconDataUri) node.icon_data_uri = iconDataUri;
        const highlight = extractHighlight(c.style);
        if (highlight) node.highlight = highlight;
        const nodeSo = extractNodeStyleOverrides(c.style, isIcon, !!highlight);
        if (nodeSo) node.style_overrides = nodeSo;
        nodes.push(node);
      }
    }
  }

  return { nodes, edges, groups, layout: layoutOptions, output_path: filePath };
}

// ─── Style classification helpers ────────────────────────────────────────────

function classifyConnector(style: string): ParsedEdge['connector'] {
  if (style.includes('edgeStyle=elbowEdgeStyle')) {
    return style.includes('elbow=horizontal') ? 'elbow-h' : 'elbow-v';
  }
  if (style.includes('edgeStyle=orthogonalEdgeStyle')) return 'orthogonal';
  // No edgeStyle → straight
  if (!style.includes('edgeStyle=')) return 'straight';
  return 'orthogonal';
}

function classifyArrow(style: string): 'default' | 'none' | 'both' {
  if (/\bendArrow=none\b/.test(style)) return 'none';
  if (/\bstartArrow=/.test(style)) return 'both';
  return 'default';
}

function classifyGroupStyle(style: string): string {
  // Reverse-lookup from buildGroupStyle() stroke colors
  const strokeMatch = style.match(/strokeColor=(#[0-9a-fA-F]{6})/);
  if (!strokeMatch) return 'green';
  const stroke = strokeMatch[1].toUpperCase();
  switch (stroke) {
    case '#0078D4': return 'blue';
    case '#E47911': return 'orange';
    case '#C62828': return 'red';
    case '#6A1B9A': return 'purple';
    case '#616161': return 'gray';
    case '#82B366': return 'green';
  }
  return stroke; // custom hex
}

function extractConnectionPoints(style: string): {
  exitX?: number; exitY?: number; entryX?: number; entryY?: number;
} {
  const result: { exitX?: number; exitY?: number; entryX?: number; entryY?: number } = {};
  const exitXm = style.match(/\bexitX=([0-9.]+)/);
  const exitYm = style.match(/\bexitY=([0-9.]+)/);
  const entryXm = style.match(/\bentryX=([0-9.]+)/);
  const entryYm = style.match(/\bentryY=([0-9.]+)/);
  if (exitXm) result.exitX = parseFloat(exitXm[1]);
  if (exitYm) result.exitY = parseFloat(exitYm[1]);
  if (entryXm) result.entryX = parseFloat(entryXm[1]);
  if (entryYm) result.entryY = parseFloat(entryYm[1]);
  return result;
}

function extractIconDataUri(style: string): string | undefined {
  // image=data:image/svg+xml,<base64> — ends at semicolon
  const m = style.match(/\bimage=(data:image\/svg\+xml[^;]+)/);
  return m ? m[1] : undefined;
}

// Named highlight colors produced by resolveColor() in mxGraphModel.ts
const HIGHLIGHT_STROKE_COLORS = new Set([
  '#c62828', '#f9a825', '#0078d4', '#e47911', '#2e7d32', '#6a1b9a',
]);

function extractHighlight(style: string): string | undefined {
  const colorMatch = style.match(/strokeColor=(#[0-9a-fA-F]{6})/);
  if (!colorMatch) return undefined;
  const color = colorMatch[1].toLowerCase();
  // Only treat as highlight if the color is from the named highlight palette.
  // Custom colors set via style_overrides.stroke_color are NOT highlights.
  if (!HIGHLIGHT_STROKE_COLORS.has(color)) return undefined;

  // For icon nodes with highlight: strokeColor=<named>;strokeWidth=3
  if (style.includes('strokeWidth=3') && style.includes('shape=image')) return colorMatch[1];
  // For rectangle nodes with default rounded: non-default named strokeColor = highlight
  if (style.includes('rounded=1;whiteSpace=wrap')) return colorMatch[1];
  return undefined;
}

// ─── style_overrides extraction ───────────────────────────────────────────────

// parseStyleMap is imported from '../utils/styleMerging.js'

/** Decompose a fontStyle bitmask into individual flags. */
function parseFontStyle(bitmask: number): Pick<NodeStyleOverrides, 'font_bold' | 'font_italic' | 'font_underline' | 'font_strikethrough'> {
  const result: Pick<NodeStyleOverrides, 'font_bold' | 'font_italic' | 'font_underline' | 'font_strikethrough'> = {};
  if (bitmask & 1) result.font_bold = true;
  if (bitmask & 2) result.font_italic = true;
  if (bitmask & 4) result.font_underline = true;
  if (bitmask & 8) result.font_strikethrough = true;
  return result;
}

/**
 * Extract node style_overrides from a drawio style string.
 * Skips properties already covered by the `highlight` field to avoid redundancy.
 */
function extractNodeStyleOverrides(style: string, isIcon: boolean, hasHighlight: boolean): NodeStyleOverrides | undefined {
  const m = parseStyleMap(style);
  const so: NodeStyleOverrides = {};

  if (!isIcon) {
    const fill = m.get('fillColor');
    if (fill && fill !== '#f5f5f5' && !hasHighlight) so.fill_color = fill;
  }

  const stroke = m.get('strokeColor');
  if (stroke) {
    const defaultStroke = isIcon ? 'none' : '#666666';
    if (stroke !== defaultStroke && !hasHighlight) so.stroke_color = stroke;
  }

  const sw = m.get('strokeWidth');
  if (sw) {
    const swNum = parseFloat(sw);
    // strokeWidth=3 is used for highlight; only capture other values
    if (!isNaN(swNum) && swNum !== 1 && !(hasHighlight && swNum === 3)) so.stroke_width = swNum;
  }

  if (m.get('dashed') === '1') so.stroke_dashed = true;

  const fontColor = m.get('fontColor');
  if (fontColor && fontColor !== '#333333') so.font_color = fontColor;

  const fontSize = m.get('fontSize');
  if (fontSize) {
    const fsNum = parseInt(fontSize);
    if (!isNaN(fsNum) && fsNum !== 11) so.font_size = fsNum;
  }

  const fontStyleRaw = m.get('fontStyle');
  if (fontStyleRaw) {
    const bits = parseInt(fontStyleRaw);
    if (!isNaN(bits) && bits > 0) Object.assign(so, parseFontStyle(bits));
  }

  const opacity = m.get('opacity');
  if (opacity) {
    const opNum = parseInt(opacity);
    if (!isNaN(opNum) && opNum !== 100) so.opacity = opNum;
  }

  if (!isIcon && m.get('rounded') === '0') so.rounded = false;
  if (m.get('shadow') === '1') so.shadow = true;

  const align = m.get('align');
  if (align && align !== 'center') so.text_align = align as 'left' | 'right';

  const vAlign = m.get('verticalAlign');
  if (!isIcon && vAlign && vAlign !== 'middle') so.text_vertical_align = vAlign as 'top' | 'bottom';

  return Object.keys(so).length > 0 ? so : undefined;
}

/** Extract edge style_overrides from a drawio style string. */
function extractEdgeStyleOverrides(style: string): EdgeStyleOverrides | undefined {
  const m = parseStyleMap(style);
  const so: EdgeStyleOverrides = {};

  const stroke = m.get('strokeColor');
  if (stroke && stroke !== '#000000') so.stroke_color = stroke;

  const sw = m.get('strokeWidth');
  if (sw) {
    const swNum = parseFloat(sw);
    if (!isNaN(swNum) && swNum !== 1) so.stroke_width = swNum;
  }

  if (m.get('dashed') === '1') so.stroke_dashed = true;

  const fontColor = m.get('fontColor');
  if (fontColor && fontColor !== '#333333') so.font_color = fontColor;

  const fontSize = m.get('fontSize');
  if (fontSize) {
    const fsNum = parseInt(fontSize);
    if (!isNaN(fsNum) && fsNum !== 11) so.font_size = fsNum;
  }

  const fontStyleRaw = m.get('fontStyle');
  if (fontStyleRaw) {
    const bits = parseInt(fontStyleRaw);
    if (!isNaN(bits) && bits > 0) {
      const flags = parseFontStyle(bits);
      if (flags.font_bold) so.font_bold = true;
      if (flags.font_italic) so.font_italic = true;
      if (flags.font_underline) so.font_underline = true;
    }
  }

  const opacity = m.get('opacity');
  if (opacity) {
    const opNum = parseInt(opacity);
    if (!isNaN(opNum) && opNum !== 100) so.opacity = opNum;
  }

  return Object.keys(so).length > 0 ? so : undefined;
}

/** Extract group style_overrides from a drawio style string. */
function extractGroupStyleOverrides(style: string): GroupStyleOverrides | undefined {
  const m = parseStyleMap(style);
  const so: GroupStyleOverrides = {};

  const fill = m.get('fillColor');
  // Skip if it matches a known palette fill (classifyGroupStyle handles the color name)
  const knownFills = new Set(['#E6F2FF', '#FFF3E0', '#FFEBEE', '#F3E5F5', '#F5F5F5', '#d5e8d4']);
  if (fill && !knownFills.has(fill)) so.fill_color = fill;

  const stroke = m.get('strokeColor');
  const knownStrokes = new Set(['#0078D4', '#E47911', '#C62828', '#6A1B9A', '#616161', '#82b366']);
  if (stroke && !knownStrokes.has(stroke.toLowerCase()) && !knownStrokes.has(stroke)) so.stroke_color = stroke;

  const sw = m.get('strokeWidth');
  if (sw) {
    const swNum = parseFloat(sw);
    if (!isNaN(swNum) && swNum !== 1) so.stroke_width = swNum;
  }

  if (m.get('dashed') === '1') so.stroke_dashed = true;
  if (m.get('rounded') === '0') so.rounded = false;

  const arcSize = m.get('arcSize');
  if (arcSize) {
    const asNum = parseInt(arcSize);
    if (!isNaN(asNum) && asNum !== 7) so.corner_radius = asNum;
  }

  const fontColor = m.get('fontColor');
  // Skip known palette font colors
  const knownFontColors = new Set(['#0078D4', '#B25000', '#C62828', '#6A1B9A', '#424242', '#333333']);
  if (fontColor && !knownFontColors.has(fontColor)) so.font_color = fontColor;

  const fontSize = m.get('fontSize');
  if (fontSize) {
    const fsNum = parseInt(fontSize);
    if (!isNaN(fsNum) && fsNum !== 11) so.font_size = fsNum;
  }

  const fontStyleRaw = m.get('fontStyle');
  if (fontStyleRaw) {
    const bits = parseInt(fontStyleRaw);
    if (!isNaN(bits)) {
      // For groups, bold=1 is the default — only record non-default combinations
      if (bits !== 1) {
        if (!(bits & 1)) so.font_bold = false;  // explicitly not bold
        if (bits & 2) so.font_italic = true;
        if (bits & 4) so.font_underline = true;
      }
    }
  }

  const opacity = m.get('opacity');
  if (opacity) {
    const opNum = parseInt(opacity);
    if (!isNaN(opNum) && opNum !== 100) so.opacity = opNum;
  }

  const align = m.get('align');
  if (align && align !== 'left') so.text_align = align as 'center' | 'right';

  const vAlign = m.get('verticalAlign');
  if (vAlign && vAlign !== 'top') so.text_vertical_align = vAlign as 'middle' | 'bottom';

  if (m.get('shadow') === '1') so.shadow = true;

  return Object.keys(so).length > 0 ? so : undefined;
}

