import fs from 'fs';
import zlib from 'zlib';
import type { LayoutOptions } from '../layout/elkLayout.js';

export interface ParsedNode {
  id: string;
  label: string;
  icon_data_uri?: string;
  highlight?: string;
  /** Absolute X coordinate extracted from mxGeometry (for INTERACTIVE ELK layout hint) */
  x_hint?: number;
  /** Absolute Y coordinate extracted from mxGeometry (for INTERACTIVE ELK layout hint) */
  y_hint?: number;
  /** Raw mxGeometry x — top-level=absolute, inside group=group-relative (for preserve mode) */
  x_geom: number;
  /** Raw mxGeometry y (for preserve mode) */
  y_geom: number;
  /** mxGeometry width (for preserve mode) */
  width: number;
  /** mxGeometry height (for preserve mode) */
  height: number;
}

export interface ParsedEdge {
  source: string;
  target: string;
  label?: string;
  style?: 'solid' | 'dashed';
  connector?: 'straight' | 'orthogonal' | 'elbow-h' | 'elbow-v';
  arrow?: 'default' | 'none' | 'both';
  exitX?: number;
  exitY?: number;
  entryX?: number;
  entryY?: number;
}

export interface ParsedGroup {
  id: string;
  label: string;
  children: string[];
  style?: string;
  /** mxGeometry x — top-level=absolute, nested=parent-relative (for preserve mode) */
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface DiagramSpec {
  nodes: ParsedNode[];
  edges: ParsedEdge[];
  groups: ParsedGroup[];
  layout?: LayoutOptions;
  output_path: string;
}

// ─── Raw cell from XML parse ─────────────────────────────────────────────────

interface RawCell {
  numericId: string;
  value: string;
  style: string;
  isVertex: boolean;
  isEdge: boolean;
  parent: string;
  source: string;
  target: string;
  x: number;
  y: number;
  width: number;
  height: number;
}

// ─── Format detection ─────────────────────────────────────────────────────────

/**
 * Detect whether a .drawio.svg file was generated by this MCP tool (Format A)
 * or created/saved by the draw.io desktop app (Format B).
 *
 * Format A: content attribute contains `<mxGraphModel>` directly (uncompressed).
 * Format B: content attribute contains `<mxfile><diagram>BASE64_COMPRESSED</diagram></mxfile>`.
 */
export function detectDrawioFormat(svgContent: string): 'A' | 'B' | 'unknown' {
  const match = svgContent.match(/\bcontent="([\s\S]*?)(?="(?:\s|\/?>|\s+data-))/);
  if (!match) return 'unknown';
  const decoded = htmlDecode(match[1]);
  if (decoded.startsWith('<mxGraphModel')) return 'A';
  if (decoded.startsWith('<mxfile')) return 'B';
  return 'unknown';
}

// ─── Public entry point ───────────────────────────────────────────────────────

export function parseDrawioSvgFile(filePath: string): DiagramSpec {
  const content = fs.readFileSync(filePath, 'utf-8');
  return parseDrawioSvgContent(content, filePath);
}

export function parseDrawioSvgContent(svgContent: string, filePath: string): DiagramSpec {
  const mxXml = extractMxGraphModelXml(svgContent);
  const layoutOptions = extractLayoutOptions(svgContent);
  const cells = parseMxCells(mxXml);
  return buildDiagramSpec(cells, layoutOptions, filePath);
}

// ─── Extract mxGraphModel XML from SVG content attribute ─────────────────────

function extractMxGraphModelXml(svgContent: string): string {
  // The content attribute may be very long; match across lines
  // It is HTML-entity encoded: &lt; &gt; &quot; &amp;
  const match = svgContent.match(/\bcontent="([\s\S]*?)(?="(?:\s|\/?>|\s+data-))/);
  if (!match) {
    throw new Error('No content attribute found in SVG file. Is this a valid .drawio.svg file?');
  }
  const decoded = htmlDecode(match[1]);

  // Format A (MCP-generated): content is directly the mxGraphModel XML
  if (decoded.startsWith('<mxGraphModel')) {
    return decoded;
  }

  // Format B (draw.io app): content is <mxfile><diagram>BASE64_COMPRESSED_XML</diagram></mxfile>
  // The diagram content is: URL-encoded XML → deflate-raw compress → base64 encode
  if (decoded.startsWith('<mxfile')) {
    const diagramMatch = decoded.match(/<diagram[^>]*>([\s\S]*?)<\/diagram>/);
    if (!diagramMatch) {
      throw new Error('Could not find <diagram> element in mxfile content.');
    }
    const base64Data = diagramMatch[1].trim();
    if (!base64Data) {
      throw new Error('Empty <diagram> content in mxfile.');
    }
    // Some draw.io versions embed the XML directly (uncompressed) inside <diagram>
    if (base64Data.startsWith('<mxGraphModel')) {
      return base64Data;
    }
    const compressed = Buffer.from(base64Data, 'base64');
    const decompressed = zlib.inflateRawSync(compressed).toString('utf-8');
    return decodeURIComponent(decompressed);
  }

  throw new Error('Unrecognized drawio content format (expected <mxGraphModel> or <mxfile>).');
}

function htmlDecode(s: string): string {
  return s
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&')
    .replace(/&#10;/g, '\n')
    .replace(/&#13;/g, '\r');
}

// ─── Extract data-layout attribute ───────────────────────────────────────────

function extractLayoutOptions(svgContent: string): LayoutOptions | undefined {
  const match = svgContent.match(/\bdata-layout='([^']+)'/);
  if (!match) return undefined;
  try {
    return JSON.parse(match[1]) as LayoutOptions;
  } catch {
    return undefined;
  }
}

// ─── Parse mxCell elements ────────────────────────────────────────────────────

function parseMxCells(xml: string): RawCell[] {
  const cells: RawCell[] = [];
  // Match each mxCell tag (self-closing or with children)
  const cellRegex = /<mxCell\s([\s\S]*?)(?:>[\s\S]*?<\/mxCell>|\/>)/g;
  let m: RegExpExecArray | null;

  while ((m = cellRegex.exec(xml)) !== null) {
    const attrs = m[1];
    const numericId = extractAttr(attrs, 'id') ?? '';
    // Skip structural cells
    if (numericId === '0' || numericId === '1') continue;

    const value = htmlDecode(extractAttr(attrs, 'value') ?? '');
    const style = extractAttr(attrs, 'style') ?? '';
    const isVertex = /\bvertex="1"/.test(attrs);
    const isEdge = /\bedge="1"/.test(attrs);
    const parent = extractAttr(attrs, 'parent') ?? '1';
    const source = extractAttr(attrs, 'source') ?? '';
    const target = extractAttr(attrs, 'target') ?? '';

    // Extract mxGeometry from the full match
    const geom = extractGeometry(m[0]);

    cells.push({
      numericId,
      value,
      style,
      isVertex,
      isEdge,
      parent,
      source,
      target,
      x: geom.x,
      y: geom.y,
      width: geom.width,
      height: geom.height,
    });
  }

  return cells;
}

function extractAttr(attrs: string, name: string): string | undefined {
  const re = new RegExp(`\\b${name}="([^"]*)"`, 'i');
  const m = re.exec(attrs);
  return m ? m[1] : undefined;
}

function extractGeometry(cellXml: string): { x: number; y: number; width: number; height: number } {
  const geomMatch = cellXml.match(/<mxGeometry\s([^>]*)(?:\/>|>)/);
  if (!geomMatch) return { x: 0, y: 0, width: 65, height: 85 };
  const g = geomMatch[1];
  return {
    x: parseFloat(extractAttr(g, 'x') ?? '0') || 0,
    y: parseFloat(extractAttr(g, 'y') ?? '0') || 0,
    width: parseFloat(extractAttr(g, 'width') ?? '65') || 65,
    height: parseFloat(extractAttr(g, 'height') ?? '85') || 85,
  };
}

// ─── Build DiagramSpec from raw cells ────────────────────────────────────────

function buildDiagramSpec(cells: RawCell[], layoutOptions: LayoutOptions | undefined, filePath: string): DiagramSpec {
  // Build a map from numericId → RawCell for fast lookup
  const byId = new Map<string, RawCell>();
  for (const c of cells) byId.set(c.numericId, c);

  // Determine which numeric IDs are group containers (have at least one child with vertex=1)
  const groupIds = new Set<string>();
  for (const c of cells) {
    if (c.isVertex && c.parent !== '1' && c.parent !== '0') {
      groupIds.add(c.parent);
    }
  }
  // Also mark groups that are children of other groups
  for (const c of cells) {
    if (c.isVertex && groupIds.has(c.numericId)) {
      // already a group — also mark its parent as a group if it's not root
      if (c.parent !== '1' && c.parent !== '0') {
        groupIds.add(c.parent);
      }
    }
  }

  // Compute absolute coordinates for each vertex cell
  const absCoords = computeAbsoluteCoords(cells, byId, groupIds);

  // Build logical ID map (label-slug → logical id), deduplicating
  const slugCount = new Map<string, number>();
  const numericToLogical = new Map<string, string>();

  const allVertices = cells.filter((c) => c.isVertex);
  for (const c of allVertices) {
    const slug = slugify(c.value || c.numericId);
    const count = (slugCount.get(slug) ?? 0) + 1;
    slugCount.set(slug, count);
    const logicalId = count === 1 ? slug : `${slug}_${count}`;
    numericToLogical.set(c.numericId, logicalId);
  }

  // Classify cells
  const nodes: ParsedNode[] = [];
  const groups: ParsedGroup[] = [];
  const edges: ParsedEdge[] = [];

  for (const c of cells) {
    if (c.isEdge) {
      const sourceLogical = numericToLogical.get(c.source);
      const targetLogical = numericToLogical.get(c.target);
      if (!sourceLogical || !targetLogical) continue; // skip dangling edges
      const arrow = classifyArrow(c.style);
      edges.push({
        source: sourceLogical,
        target: targetLogical,
        label: c.value || undefined,
        style: c.style.includes('dashed=1') ? 'dashed' : 'solid',
        connector: classifyConnector(c.style),
        ...(arrow !== 'default' ? { arrow } : {}),
        ...extractConnectionPoints(c.style),
      });
    } else if (c.isVertex) {
      const logicalId = numericToLogical.get(c.numericId)!;
      if (groupIds.has(c.numericId)) {
        // Group cell
        const childrenNumerics = cells
          .filter((child) => child.isVertex && child.parent === c.numericId)
          .map((child) => numericToLogical.get(child.numericId)!)
          .filter(Boolean);
        groups.push({
          id: logicalId,
          label: c.value,
          children: childrenNumerics,
          style: classifyGroupStyle(c.style),
          x: c.x,
          y: c.y,
          width: c.width,
          height: c.height,
        });
      } else {
        // Node cell
        const abs = absCoords.get(c.numericId) ?? { x: c.x, y: c.y };
        const node: ParsedNode = {
          id: logicalId,
          label: c.value,
          x_hint: abs.x,
          y_hint: abs.y,
          x_geom: c.x,
          y_geom: c.y,
          width: c.width,
          height: c.height,
        };
        const iconDataUri = extractIconDataUri(c.style);
        if (iconDataUri) node.icon_data_uri = iconDataUri;
        const highlight = extractHighlight(c.style);
        if (highlight) node.highlight = highlight;
        nodes.push(node);
      }
    }
  }

  return { nodes, edges, groups, layout: layoutOptions, output_path: filePath };
}

// ─── Absolute coordinate computation ─────────────────────────────────────────

function computeAbsoluteCoords(
  cells: RawCell[],
  byId: Map<string, RawCell>,
  groupIds: Set<string>,
): Map<string, { x: number; y: number }> {
  const result = new Map<string, { x: number; y: number }>();

  function getAbsolutePos(numericId: string, visited = new Set<string>()): { x: number; y: number } {
    if (result.has(numericId)) return result.get(numericId)!;
    if (visited.has(numericId)) return { x: 0, y: 0 }; // cycle guard
    visited.add(numericId);

    const cell = byId.get(numericId);
    if (!cell) return { x: 0, y: 0 };

    if (cell.parent === '1' || cell.parent === '0') {
      // Top-level: coordinates are absolute
      const pos = { x: cell.x, y: cell.y };
      result.set(numericId, pos);
      return pos;
    }

    // Relative: add parent's absolute position
    const parentPos = getAbsolutePos(cell.parent, visited);
    const pos = { x: parentPos.x + cell.x, y: parentPos.y + cell.y };
    result.set(numericId, pos);
    return pos;
  }

  for (const cell of cells) {
    if (cell.isVertex && !groupIds.has(cell.numericId)) {
      getAbsolutePos(cell.numericId);
    }
  }

  return result;
}

// ─── Style classification helpers ────────────────────────────────────────────

function classifyConnector(style: string): ParsedEdge['connector'] {
  if (style.includes('edgeStyle=elbowEdgeStyle')) {
    return style.includes('elbow=horizontal') ? 'elbow-h' : 'elbow-v';
  }
  if (style.includes('edgeStyle=orthogonalEdgeStyle')) return 'orthogonal';
  // No edgeStyle → straight
  if (!style.includes('edgeStyle=')) return 'straight';
  return 'orthogonal';
}

function classifyArrow(style: string): 'default' | 'none' | 'both' {
  if (/\bendArrow=none\b/.test(style)) return 'none';
  if (/\bstartArrow=/.test(style)) return 'both';
  return 'default';
}

function classifyGroupStyle(style: string): string {
  // Reverse-lookup from buildGroupStyle() stroke colors
  const strokeMatch = style.match(/strokeColor=(#[0-9a-fA-F]{6})/);
  if (!strokeMatch) return 'green';
  const stroke = strokeMatch[1].toUpperCase();
  switch (stroke) {
    case '#0078D4': return 'blue';
    case '#E47911': return 'orange';
    case '#C62828': return 'red';
    case '#6A1B9A': return 'purple';
    case '#616161': return 'gray';
    case '#82B366': return 'green';
  }
  return stroke; // custom hex
}

function extractConnectionPoints(style: string): {
  exitX?: number; exitY?: number; entryX?: number; entryY?: number;
} {
  const result: { exitX?: number; exitY?: number; entryX?: number; entryY?: number } = {};
  const exitXm = style.match(/\bexitX=([0-9.]+)/);
  const exitYm = style.match(/\bexitY=([0-9.]+)/);
  const entryXm = style.match(/\bentryX=([0-9.]+)/);
  const entryYm = style.match(/\bentryY=([0-9.]+)/);
  if (exitXm) result.exitX = parseFloat(exitXm[1]);
  if (exitYm) result.exitY = parseFloat(exitYm[1]);
  if (entryXm) result.entryX = parseFloat(entryXm[1]);
  if (entryYm) result.entryY = parseFloat(entryYm[1]);
  return result;
}

function extractIconDataUri(style: string): string | undefined {
  // image=data:image/svg+xml,<base64> — ends at semicolon
  const m = style.match(/\bimage=(data:image\/svg\+xml[^;]+)/);
  return m ? m[1] : undefined;
}

function extractHighlight(style: string): string | undefined {
  // For icon nodes with highlight: strokeColor=#XXXXXX;strokeWidth=3
  if (style.includes('strokeWidth=3')) {
    const m = style.match(/strokeColor=(#[0-9a-fA-F]{6})/);
    if (m) return m[1];
  }
  // For rectangle nodes: strokeColor differs from default #666666
  if (style.includes('rounded=1;whiteSpace=wrap')) {
    const m = style.match(/strokeColor=(#[0-9a-fA-F]{6})/);
    if (m && m[1].toUpperCase() !== '#666666') return m[1];
  }
  return undefined;
}

// ─── Slug utility ─────────────────────────────────────────────────────────────

function slugify(label: string): string {
  return label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '') || 'node';
}
